source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
target 'UnsplashKit_Tests' do
  pod 'UnsplashKit', :path => '../'

  pod 'Quick', '~> 0.9'
  pod 'Nimble', '~> 3.0'
  pod 'Mockingjay', '~> 1.2.1'
end
