source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
target 'UnsplashKit_Tests' do
  pod 'UnsplashKit/Source', :path => '../'
  pod 'UnsplashKit/API', :path => '../'
  pod 'Quick', '~> 0.9'
  pod 'Nimble', '~> 5.0'
  pod 'OHHTTPStubs', '~> 5.2.1'
  pod 'OHHTTPStubs/Swift', '~> 5.2.1'
end
