disabled_rules:
  - colon
  - comma
  - control_statement
  - force_cast
included:
  - ../UnsplashKit
excluded:
  - ../Example
  - ../fastlane
force_cast: warning
force_try:
  severity: warning
line_length: 180
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
variable_name:
  min_length:
    error: 3
reporter: "xcode"