COMMIT_MESSAGE = "Bump podspec to"

lane :pods do
  cocoapods(podfile: "Example/")
end

lane :tests do
  scan(workspace: "Example/UnsplashKit.xcworkspace", scheme: "UnsplashKit-Example", clean: true)
end

lane :travis do
  pods
  tests
  pod_lib_lint(allow_warnings: true, verbose: true)
end

lane :push do
  ensure_git_branch
  version = version_bump_podspec(path: "UnsplashKit.podspec")
  git_commit(path: ["./UnsplashKit.podspec", "./Example/Podfile.lock"], message: "#{COMMIT_MESSAGE} #{version}")
  changelog = changelog_from_git_commits
  github_release = set_github_release(
    repository_name: "carambalabs/UnsplashKit",
    api_token: ENV['GITHUB_TOKEN'],
    name: version,
    tag_name: version,
    description: changelog,
    commitish: "master"
  )
  push_to_git_remote(remote_branch: 'master', force: false, tags: true)
  pod_push(allow_warnings: true, verbose: true)
  pod_push(path: 'UnsplashKit.podspec', verbose: true, allow_warnings: true, repo: 'carambalabs', sources: ['https://github.com/carambalabs/Specs', 'https://github.com/CocoaPods/Specs'])
end
